/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js type tooling. Keep it committed so fresh
// checkouts have the expected ambient types before the first local dev run.
