export type SourceId =
  | "ncei-nwp"
  | "noaa-gfs"
  | "nws-observations"
  | "ecmwf-ifs"
  | "ecmwf-ensemble"
  | "ecmwf-ai-ensemble"
  | "wmo-verification";

export type DocBlock =
  | { kind: "lead"; text: string }
  | { kind: "paragraph"; text: string }
  | { kind: "list"; title?: string; items: string[] }
  | { kind: "flow"; title?: string; steps: string[] }
  | { kind: "table"; title?: string; columns: string[]; rows: string[][] }
  | { kind: "formula"; title?: string; expression: string; description?: string }
  | { kind: "callout"; title: string; text: string }
  | { kind: "code"; title?: string; code: string };

export type DocSection = {
  title: string;
  blocks: DocBlock[];
};

export type DocPage = {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  group: "Weather Prediction" | "Platform Architecture";
  references?: SourceId[];
  sections: DocSection[];
};

export const sourceLinks: Record<SourceId, { label: string; href: string; publisher: string }> = {
  "ncei-nwp": {
    label: "Numerical Weather Prediction",
    href: "https://www.ncei.noaa.gov/products/weather-climate-models/numerical-weather-prediction",
    publisher: "NOAA NCEI"
  },
  "noaa-gfs": {
    label: "Global Forecast System",
    href: "https://www.emc.ncep.noaa.gov/emc/pages/numerical_forecast_systems/gfs.php",
    publisher: "NOAA NCEP EMC"
  },
  "nws-observations": {
    label: "NOAA Observation Systems",
    href: "https://www.weather.gov/about/observation-equipment",
    publisher: "National Weather Service"
  },
  "ecmwf-ifs": {
    label: "Integrated Forecasting System",
    href: "https://www.ecmwf.int/en/forecasts/documentation-and-support/changes-ecmwf-model",
    publisher: "ECMWF"
  },
  "ecmwf-ensemble": {
    label: "Ensemble forecasts at ECMWF",
    href: "https://www.ecmwf.int/en/about/media-centre/media-resources/tim-palmer-festschrift/Ensemble-forecasts-at-ECMWF-in-the-presence-and-future",
    publisher: "ECMWF"
  },
  "ecmwf-ai-ensemble": {
    label: "Ensemble AI forecasts become operational",
    href: "https://www.ecmwf.int/en/about/media-centre/news/2025/ecmwfs-ensemble-ai-forecasts-become-operational",
    publisher: "ECMWF"
  },
  "wmo-verification": {
    label: "Forecast Verifications",
    href: "https://community.wmo.int/site/knowledge-hub/programmes-and-initiatives/wmo-integrated-processing-and-prediction-system-wipps/forecast-verifications",
    publisher: "WMO"
  }
};

export const docsIntro =
  "Weather AI transforms official forecast-model output into structured probability, confidence, and edge signals. It ingests numerical weather prediction data, compares model runs, measures uncertainty, verifies historical accuracy, and converts raw weather forecasts into decision-grade intelligence for cities, events, and prediction markets.";

export const technicalSummary =
  "Supercomputer weather forecasts are generated by numerical models that estimate the current atmosphere through data assimilation, divide the Earth system into a three-dimensional grid, solve physical equations forward in time, and produce deterministic and probabilistic forecasts. AI systems can improve this process by calibrating model output, correcting bias, detecting forecast instability, and translating ensemble information into actionable probabilities.";

export const docs: DocPage[] = [
  {
    slug: "weather-prediction-overview",
    title: "Weather Prediction Overview",
    shortTitle: "Overview",
    description: "The end-to-end forecast chain, from observations to probabilistic weather and market intelligence.",
    group: "Weather Prediction",
    references: ["ncei-nwp"],
    sections: [
      {
        title: "Modern Forecasting",
        blocks: [
          {
            kind: "lead",
            text: "Modern weather prediction is a computational simulation of the Earth system. Forecast centers collect observations, estimate the current atmosphere, and run numerical models forward in time on supercomputers."
          },
          {
            kind: "paragraph",
            text: "Numerical weather prediction uses current observations and model physics to forecast temperature, precipitation, pressure, wind, humidity, cloud cover, ocean conditions, and many other variables. A useful platform should treat that output as a structured estimate of many possible future states, not as a single number."
          },
          {
            kind: "flow",
            title: "The basic forecast chain",
            steps: [
              "Observations",
              "Quality control",
              "Data assimilation",
              "Initial atmospheric state",
              "Numerical weather model",
              "Supercomputer simulation",
              "Deterministic and ensemble forecasts",
              "Post-processing",
              "Verification",
              "Decision signals"
            ]
          }
        ]
      },
      {
        title: "The Core Disciplines",
        blocks: [
          {
            kind: "table",
            columns: ["Discipline", "Role"],
            rows: [
              ["Atmospheric physics", "Describes how air, water, heat, and pressure evolve."],
              ["High-performance computing", "Runs global simulations fast enough to be operationally useful."],
              ["Statistics and AI", "Corrects bias, estimates uncertainty, and converts forecasts into probabilities."]
            ]
          },
          {
            kind: "callout",
            title: "Platform objective",
            text: "The application should not only display the forecast. It should convert forecast-model output into probability, confidence, risk, and transparent model-market disagreement."
          }
        ]
      }
    ]
  },
  {
    slug: "supercomputers-and-weather-models",
    title: "Supercomputers and Weather Models",
    shortTitle: "Supercomputers",
    description: "Why operational weather prediction depends on high-performance computing and fast forecast cycles.",
    group: "Weather Prediction",
    references: ["noaa-gfs"],
    sections: [
      {
        title: "Why Supercomputers Are Needed",
        blocks: [
          {
            kind: "lead",
            text: "Weather models are computationally expensive because they simulate the atmosphere in three dimensions across the entire Earth."
          },
          {
            kind: "list",
            title: "A global model calculates",
            items: [
              "Wind movement, pressure gradients, and moisture transport.",
              "Radiation, clouds, precipitation, turbulence, and surface friction.",
              "Land-atmosphere, ocean-atmosphere, ice, and snow processes.",
              "Many forecast hours across many ensemble members."
            ]
          },
          {
            kind: "formula",
            title: "Operational value",
            expression: "Forecast value = Accuracy * Timeliness",
            description: "A forecast cycle has a deadline. Accurate output that arrives too late has limited operational value."
          }
        ]
      },
      {
        title: "Forecast Cycle Workload",
        blocks: [
          {
            kind: "table",
            columns: ["Workload", "Description"],
            rows: [
              ["Data ingest", "Pull observations from satellites, stations, radar, aircraft, buoys, balloons, and model feeds."],
              ["Quality control", "Remove bad, delayed, duplicated, or inconsistent observations."],
              ["Data assimilation", "Combine observations with a previous model background state."],
              ["Forecast integration", "Run physical equations forward in time."],
              ["Ensemble generation", "Run perturbed versions of the forecast to estimate uncertainty."],
              ["Post-processing", "Convert raw fields into products, probabilities, and calibrated signals."],
              ["Dissemination", "Publish data to APIs, charts, applications, and downstream systems."]
            ]
          },
          {
            kind: "callout",
            title: "Cloud server boundary",
            text: "A normal web server can serve forecast data. It usually cannot run a full global operational model at competitive resolution, cadence, and reliability."
          }
        ]
      }
    ]
  },
  {
    slug: "observing-the-atmosphere",
    title: "Observing the Atmosphere",
    shortTitle: "Observations",
    description: "How satellites, stations, radar, balloons, aircraft, and ocean sensors initialize forecast models.",
    group: "Weather Prediction",
    references: ["nws-observations"],
    sections: [
      {
        title: "Measurement Sources",
        blocks: [
          {
            kind: "lead",
            text: "Before a model can predict the future, it must estimate the present. Weather observations provide the raw evidence for that estimate."
          },
          {
            kind: "table",
            columns: ["Source", "What it measures"],
            rows: [
              ["Satellites", "Clouds, temperature profiles, water vapor, sea surface temperature, and atmospheric motion."],
              ["Weather stations", "Surface temperature, pressure, wind, humidity, and precipitation."],
              ["Radar", "Precipitation intensity, storm structure, and velocity."],
              ["Weather balloons", "Vertical profiles of temperature, wind, humidity, and pressure."],
              ["Aircraft", "Upper-air temperature and wind observations."],
              ["Ocean buoys and ships", "Sea-level pressure, waves, sea surface temperature, and marine winds."],
              ["Remote sensors", "Radiation, moisture, aerosols, and atmospheric composition."]
            ]
          }
        ]
      },
      {
        title: "The Observation Problem",
        blocks: [
          {
            kind: "paragraph",
            text: "The atmosphere is not fully observed. Oceans, polar regions, sparse ground stations, instrument errors, delayed data, satellite retrieval uncertainty, and vertical resolution limits all leave gaps."
          },
          {
            kind: "callout",
            title: "Why assimilation exists",
            text: "Forecast centers cannot simply measure the whole atmosphere. They must estimate a complete physical state from incomplete and noisy evidence."
          }
        ]
      }
    ]
  },
  {
    slug: "data-assimilation",
    title: "Data Assimilation",
    shortTitle: "Data Assimilation",
    description: "How models combine observations with a previous forecast to create the initial atmospheric state.",
    group: "Weather Prediction",
    references: ["ecmwf-ifs"],
    sections: [
      {
        title: "The Analysis State",
        blocks: [
          {
            kind: "lead",
            text: "Data assimilation combines observations with a recent short-range forecast to produce the best estimate of the current atmosphere."
          },
          {
            kind: "formula",
            title: "Atmospheric state vector",
            expression: "x = [temperature, pressure, wind, humidity, clouds, rain, snow, ice, soil, ocean, radiation]",
            description: "The model needs a complete state, even though observations are incomplete."
          },
          {
            kind: "formula",
            title: "Assimilation identity",
            expression: "Previous forecast + New observations + Error estimates = Analysis",
            description: "The analysis is the initial condition for the next forecast run."
          }
        ]
      },
      {
        title: "Variational Objective",
        blocks: [
          {
            kind: "formula",
            title: "Objective function",
            expression: "J(x) = (x - x_b)^T B^-1 (x - x_b) + (y - H(x))^T R^-1 (y - H(x))",
            description: "The first term penalizes distance from the background forecast. The second term penalizes mismatch with observations."
          },
          {
            kind: "table",
            columns: ["Symbol", "Meaning"],
            rows: [
              ["x", "Atmospheric state being estimated."],
              ["x_b", "Background state from a previous short-range forecast."],
              ["B", "Background error covariance."],
              ["y", "Observation vector."],
              ["H(x)", "Observation operator that maps model state to observable values."],
              ["R", "Observation error covariance."]
            ]
          },
          {
            kind: "callout",
            title: "Plain-English version",
            text: "Find the atmospheric state that is close to the previous forecast, close to the new observations, and weighted by how much each input is trusted."
          }
        ]
      }
    ]
  },
  {
    slug: "numerical-weather-prediction",
    title: "Numerical Weather Prediction",
    shortTitle: "Numerical Models",
    description: "How models move the atmospheric state forward through physical equations and numerical time steps.",
    group: "Weather Prediction",
    references: ["ncei-nwp", "noaa-gfs"],
    sections: [
      {
        title: "Forecast Integration",
        blocks: [
          {
            kind: "lead",
            text: "Numerical weather prediction starts with the analysis state and advances it through time using a model that approximates atmospheric physics."
          },
          {
            kind: "formula",
            title: "Forecast update equation",
            expression: "x(t + dt) = M(x(t), forcing, physics, boundary_conditions)",
            description: "M represents the numerical model. It updates the state using dynamics, physics, and boundary conditions."
          },
          {
            kind: "formula",
            title: "State vector",
            expression: "x = [u, v, w, T, p, q, cloud_water, rain, snow, soil_moisture, sea_surface_temperature]",
            description: "The exact vector differs by model, but the principle is the same: track the atmosphere and connected surface systems."
          }
        ]
      },
      {
        title: "Why Small Errors Grow",
        blocks: [
          {
            kind: "paragraph",
            text: "Weather systems are chaotic. Tiny errors in initial conditions can grow as the forecast moves forward. This is why forecast confidence normally decreases with lead time."
          },
          {
            kind: "formula",
            title: "Error growth",
            expression: "error(t) ~= error(0) * e^(lambda * t)",
            description: "The growth rate lambda varies by weather regime. Fast-moving storms and convective systems often have higher uncertainty."
          },
          {
            kind: "callout",
            title: "Product implication",
            text: "The interface should show forecast time, model run time, and confidence decay rather than implying every forecast hour has equal certainty."
          }
        ]
      }
    ]
  },
  {
    slug: "model-physics",
    title: "Model Physics",
    shortTitle: "Model Physics",
    description: "The physical processes represented directly or through parameterizations in weather models.",
    group: "Weather Prediction",
    sections: [
      {
        title: "Core Equations",
        blocks: [
          {
            kind: "lead",
            text: "A weather model is a numerical approximation of fluid motion, thermodynamics, moisture, radiation, and surface exchange."
          },
          {
            kind: "table",
            columns: ["Process", "Representative relationship"],
            rows: [
              ["Momentum", "Dv/Dt = -1/rho * grad(p) + gravity + friction + rotation"],
              ["Mass continuity", "Drho/Dt + rho * div(v) = 0"],
              ["Thermodynamics", "DT/Dt = heating/cp + advection + mixing"],
              ["Moisture", "Dq/Dt = evaporation - condensation + transport"],
              ["Radiation", "Net radiation = shortwave_in - shortwave_out + longwave_in - longwave_out"],
              ["Surface exchange", "Flux = transfer_coefficient * wind * surface_gradient"]
            ]
          }
        ]
      },
      {
        title: "Parameterized Processes",
        blocks: [
          {
            kind: "paragraph",
            text: "Not every process can be resolved directly at the model grid scale. Smaller-scale behavior is represented through parameterization schemes."
          },
          {
            kind: "list",
            items: [
              "Convection and thunderstorms.",
              "Cloud microphysics and precipitation formation.",
              "Turbulence and boundary-layer mixing.",
              "Land surface, snow, vegetation, and soil exchange.",
              "Ocean, wave, and sea-ice coupling."
            ]
          },
          {
            kind: "callout",
            title: "Why models disagree",
            text: "Different models can share the same observations but diverge because they use different grids, physics packages, assimilation choices, and post-processing."
          }
        ]
      }
    ]
  },
  {
    slug: "grid-resolution-and-time-stepping",
    title: "Grid Resolution and Time Stepping",
    shortTitle: "Grid + Time Steps",
    description: "How grid spacing, vertical layers, and stable time steps shape forecast accuracy and cost.",
    group: "Weather Prediction",
    sections: [
      {
        title: "Resolution Tradeoffs",
        blocks: [
          {
            kind: "lead",
            text: "A weather model divides the Earth system into horizontal grid cells and vertical layers. Smaller grid cells can represent finer structure, but they cost much more to run."
          },
          {
            kind: "formula",
            title: "Grid point scaling",
            expression: "grid_points ~= earth_area / dx^2 * vertical_layers",
            description: "Halving horizontal grid spacing can roughly quadruple horizontal grid cells before time-step costs are considered."
          },
          {
            kind: "table",
            columns: ["Smaller grid spacing", "Tradeoff"],
            rows: [
              ["More local detail", "Can better represent fronts, terrain, coastlines, and storms."],
              ["Higher compute cost", "More grid cells, more memory, and shorter time steps."],
              ["Not automatically better", "Errors can still come from initial state, physics, and observations."]
            ]
          }
        ]
      },
      {
        title: "Time Step Stability",
        blocks: [
          {
            kind: "formula",
            title: "CFL condition",
            expression: "C = u * dt / dx <= C_max",
            description: "For numerical stability, information should not move too far across the grid during a single time step."
          },
          {
            kind: "formula",
            title: "Time stepping",
            expression: "x_n+1 = x_n + dt * F(x_n)",
            description: "F is the model tendency: the estimated rate of change from dynamics and physics."
          },
          {
            kind: "callout",
            title: "Product implication",
            text: "Resolution, lead time, model cycle, and update cadence should be visible when users compare forecasts."
          }
        ]
      }
    ]
  },
  {
    slug: "ensemble-forecasting",
    title: "Ensemble Forecasting",
    shortTitle: "Ensembles",
    description: "How many forecast members produce event probabilities, spread, and uncertainty estimates.",
    group: "Weather Prediction",
    references: ["ecmwf-ensemble"],
    sections: [
      {
        title: "Ensemble Concept",
        blocks: [
          {
            kind: "lead",
            text: "An ensemble forecast runs many related forecasts instead of one deterministic forecast. Each member perturbs initial conditions, model physics, or both."
          },
          {
            kind: "flow",
            title: "Example rain probability",
            steps: ["50 ensemble members", "38 predict rain", "12 predict no rain", "Rain probability = 38 / 50 = 76%"]
          },
          {
            kind: "formula",
            title: "Event probability",
            expression: "P(event) = count(members where event occurs) / total_members",
            description: "Ensembles convert model disagreement into a probability distribution."
          }
        ]
      },
      {
        title: "Mean and Spread",
        blocks: [
          {
            kind: "formula",
            title: "Ensemble mean",
            expression: "mean = (1/N) * sum(x_i)",
            description: "The average forecast across members."
          },
          {
            kind: "formula",
            title: "Ensemble spread",
            expression: "spread = sqrt((1/N) * sum((x_i - mean)^2))",
            description: "A measure of member disagreement."
          },
          {
            kind: "callout",
            title: "Market relevance",
            text: "For prediction markets, ensembles help estimate whether market probability is aligned with model probability or pricing a different risk view."
          }
        ]
      }
    ]
  },
  {
    slug: "forecast-uncertainty",
    title: "Forecast Uncertainty",
    shortTitle: "Uncertainty",
    description: "How volatility, model disagreement, lead time, and verification shape confidence scores.",
    group: "Weather Prediction",
    sections: [
      {
        title: "Sources of Uncertainty",
        blocks: [
          {
            kind: "lead",
            text: "A forecast is uncertain because the atmosphere is only partially observed, model physics are approximate, and small errors can grow over time."
          },
          {
            kind: "list",
            items: [
              "Initial condition error from incomplete observations.",
              "Model error from simplified physics and finite grid resolution.",
              "Boundary condition error from land, ocean, and upstream model inputs.",
              "Lead-time decay as forecast hours move farther from the analysis state.",
              "Regime risk when storms, fronts, or convective systems change rapidly."
            ]
          }
        ]
      },
      {
        title: "Confidence Scoring",
        blocks: [
          {
            kind: "formula",
            title: "Forecast volatility",
            expression: "V = stddev(model_run_values over recent cycles)",
            description: "Large cycle-to-cycle changes indicate an unstable forecast."
          },
          {
            kind: "formula",
            title: "Model disagreement",
            expression: "D = stddev([GFS_value, ECMWF_value, OpenMeteo_value, AI_value])",
            description: "Different providers or model families can disagree even for the same city and valid time."
          },
          {
            kind: "formula",
            title: "Confidence score",
            expression: "confidence = clamp(1 - (w1 * lead_time + w2 * spread + w3 * disagreement + w4 * volatility), 0, 1)",
            description: "A practical application score can combine lead time, ensemble spread, cross-model disagreement, and recent volatility."
          },
          {
            kind: "callout",
            title: "Product meaning",
            text: "A high confidence score means the system sees a stable, well-supported forecast. It is not a guarantee that the event will occur."
          }
        ]
      }
    ]
  },
  {
    slug: "ai-weather-models",
    title: "AI Weather Models",
    shortTitle: "AI Models",
    description: "Where AI can help weather prediction and where physics, verification, and guardrails still matter.",
    group: "Weather Prediction",
    references: ["ecmwf-ai-ensemble"],
    sections: [
      {
        title: "Physics Models vs AI Models",
        blocks: [
          {
            kind: "lead",
            text: "AI weather systems can learn forecast patterns from historical model output and observations. They are useful for calibration, speed, post-processing, and pattern recognition, but they should not be treated as magic."
          },
          {
            kind: "table",
            columns: ["Model family", "Strength"],
            rows: [
              ["Physics-based NWP", "Grounded in atmospheric equations, operational assimilation, and physical constraints."],
              ["AI forecast models", "Fast inference, learned pattern correction, and strong post-processing potential."],
              ["Hybrid systems", "Combine physics output, observations, ensembles, verification history, and learned calibration."]
            ]
          }
        ]
      },
      {
        title: "Adjustment and Bias Correction",
        blocks: [
          {
            kind: "formula",
            title: "AI forecast adjustment",
            expression: "y_hat = f(model_fields, observations, terrain, seasonality, history, market_context)",
            description: "The AI system maps raw data and context to a calibrated estimate."
          },
          {
            kind: "formula",
            title: "Bias correction",
            expression: "corrected = model_forecast - learned_bias(city, variable, lead_time, season)",
            description: "Bias correction should be verified separately by city, weather variable, lead time, and season."
          },
          {
            kind: "callout",
            title: "Guardrail",
            text: "AI outputs should be compared against official model fields, ensemble spread, and historical verification before they influence market-facing signals."
          }
        ]
      }
    ]
  },
  {
    slug: "model-verification",
    title: "Model Verification",
    shortTitle: "Verification",
    description: "How forecast quality is measured with error metrics, probability scores, and skill scores.",
    group: "Weather Prediction",
    references: ["wmo-verification"],
    sections: [
      {
        title: "Why Verification Matters",
        blocks: [
          {
            kind: "lead",
            text: "Verification compares forecast output with what actually happened. Without verification, a platform cannot know which models, horizons, variables, or cities are reliable."
          },
          {
            kind: "table",
            columns: ["Question", "Metric type"],
            rows: [
              ["How far was the forecast from the observed value?", "Error metrics such as MAE and RMSE."],
              ["Was the model systematically too warm, wet, or windy?", "Bias metrics."],
              ["Were event probabilities calibrated?", "Brier score and reliability diagnostics."],
              ["Did the model beat a baseline?", "Skill score against climatology, persistence, or another model."]
            ]
          }
        ]
      },
      {
        title: "Core Metrics",
        blocks: [
          {
            kind: "formula",
            title: "Mean Absolute Error",
            expression: "MAE = (1/N) * sum(abs(forecast_i - observed_i))"
          },
          {
            kind: "formula",
            title: "Root Mean Square Error",
            expression: "RMSE = sqrt((1/N) * sum((forecast_i - observed_i)^2))"
          },
          {
            kind: "formula",
            title: "Bias",
            expression: "Bias = (1/N) * sum(forecast_i - observed_i)"
          },
          {
            kind: "formula",
            title: "Brier Score",
            expression: "BS = (1/N) * sum((probability_i - outcome_i)^2)"
          },
          {
            kind: "formula",
            title: "Forecast skill score",
            expression: "Skill = 1 - (model_error / reference_error)",
            description: "A positive score means the model beats the reference forecast."
          }
        ]
      }
    ]
  },
  {
    slug: "weather-data-pipeline",
    title: "Weather Data Pipeline",
    shortTitle: "Data Pipeline",
    description: "A production-oriented pipeline for ingesting official forecasts, markets, signals, and verification data.",
    group: "Platform Architecture",
    sections: [
      {
        title: "Recommended Pipeline",
        blocks: [
          {
            kind: "lead",
            text: "The platform should separate collection, normalization, storage, signal computation, and presentation. That keeps provider changes from leaking into the user interface."
          },
          {
            kind: "flow",
            steps: [
              "Provider APIs",
              "Fetcher jobs",
              "Normalization and validation",
              "Database storage",
              "Signal computation",
              "API routes",
              "Map and docs UI",
              "Verification and monitoring"
            ]
          },
          {
            kind: "list",
            title: "Required metadata",
            items: [
              "Provider name, model family, run time, valid time, and ingestion time.",
              "City, latitude, longitude, variable, units, and forecast horizon.",
              "Raw provider URL or source identifier for traceability.",
              "Quality-control flags and normalization version.",
              "Market provider, market id, question, close time, liquidity, and price snapshot time."
            ]
          }
        ]
      },
      {
        title: "Database Surface",
        blocks: [
          {
            kind: "table",
            columns: ["Table", "Purpose"],
            rows: [
              ["cities", "Canonical city metadata and map coordinates."],
              ["forecast_points", "Normalized weather model points by city, variable, valid time, and provider."],
              ["market_events", "Prediction-market questions mapped to weather events and cities."],
              ["market_history", "Price, volume, and liquidity snapshots over time."],
              ["combined_signals", "Model probability, market probability, edge, confidence, and signal state."],
              ["verification_observations", "Observed outcomes used for forecast and market-signal scoring."]
            ]
          },
          {
            kind: "callout",
            title: "Operational rule",
            text: "Keep raw provider details out of UI components. The UI should consume normalized domain records from API routes or server data loaders."
          }
        ]
      }
    ]
  },
  {
    slug: "prediction-market-weather-signals",
    title: "Prediction Market Weather Signals",
    shortTitle: "Prediction Markets",
    description: "How model probabilities can be compared with market-implied probabilities without presenting trading advice.",
    group: "Platform Architecture",
    sections: [
      {
        title: "Model-Market Comparison",
        blocks: [
          {
            kind: "lead",
            text: "Prediction-market prices can be interpreted as market-implied probabilities, while weather models estimate event probabilities from forecast data. The useful product signal is the transparent comparison between the two."
          },
          {
            kind: "formula",
            title: "Market probability",
            expression: "P_market ~= best_yes_price",
            description: "For simple binary markets, the yes price is often used as a probability proxy before fees, spreads, and liquidity are considered."
          },
          {
            kind: "formula",
            title: "Model edge",
            expression: "edge = P_model - P_market"
          },
          {
            kind: "code",
            title: "Example",
            code: "P_model = 0.72\nP_market = 0.58\nedge = 0.14"
          }
        ]
      },
      {
        title: "Risk-Adjusted Signals",
        blocks: [
          {
            kind: "formula",
            title: "Confidence-adjusted edge",
            expression: "adjusted_edge = edge * confidence"
          },
          {
            kind: "formula",
            title: "Liquidity-aware edge",
            expression: "liquidity_adjusted_edge = adjusted_edge - fees - estimated_slippage"
          },
          {
            kind: "table",
            columns: ["State", "Meaning"],
            rows: [
              ["Aligned", "Model probability and market probability are close."],
              ["Watch", "Moderate difference or low confidence."],
              ["Divergent", "Large difference with adequate confidence and data quality."],
              ["Stale", "Market or forecast data is too old to compare."],
              ["Unavailable", "Missing model, market, or mapping data."]
            ]
          },
          {
            kind: "callout",
            title: "No trading advice",
            text: "Signals should explain model-market disagreement and data quality. They should not tell users to trade or imply guaranteed profit."
          }
        ]
      },
      {
        title: "Weather-Specific Market Risks",
        blocks: [
          {
            kind: "list",
            items: [
              "Market resolution rules may not match the model variable exactly.",
              "Station choice, city boundary, observation source, and time window can change the result.",
              "Forecast data can update faster than market liquidity.",
              "Extreme events can break historical calibration.",
              "Prediction-market access and trading can be restricted by jurisdiction."
            ]
          }
        ]
      }
    ]
  },
  {
    slug: "formulas",
    title: "Forecast Model Formula Reference",
    shortTitle: "Formula Reference",
    description: "A compact reference for model dynamics, assimilation, ensembles, verification, and market-signal math.",
    group: "Platform Architecture",
    sections: [
      {
        title: "Atmospheric Equations",
        blocks: [
          { kind: "formula", title: "Momentum", expression: "Dv/Dt = -1/rho * grad(p) + gravity + coriolis + friction" },
          { kind: "formula", title: "Continuity", expression: "Drho/Dt + rho * div(v) = 0" },
          { kind: "formula", title: "Thermodynamic energy", expression: "DT/Dt = Q/cp - advection + mixing" },
          { kind: "formula", title: "Moisture", expression: "Dq/Dt = E - C + transport" },
          { kind: "formula", title: "Surface flux", expression: "Flux = C_d * wind * gradient" }
        ]
      },
      {
        title: "Numerical Methods",
        blocks: [
          { kind: "formula", title: "Time update", expression: "x_n+1 = x_n + dt * F(x_n)" },
          { kind: "formula", title: "CFL stability", expression: "C = u * dt / dx <= C_max" },
          { kind: "formula", title: "Resolution scaling", expression: "cost grows with grid_cells * vertical_layers * time_steps * ensemble_members" }
        ]
      },
      {
        title: "Assimilation and Ensembles",
        blocks: [
          { kind: "formula", title: "Assimilation objective", expression: "J(x) = background_mismatch + observation_mismatch" },
          { kind: "formula", title: "Ensemble probability", expression: "P(event) = event_members / total_members" },
          { kind: "formula", title: "Ensemble mean", expression: "mean = (1/N) * sum(x_i)" },
          { kind: "formula", title: "Ensemble spread", expression: "spread = sqrt((1/N) * sum((x_i - mean)^2))" }
        ]
      },
      {
        title: "Verification and Markets",
        blocks: [
          { kind: "formula", title: "MAE", expression: "MAE = (1/N) * sum(abs(forecast_i - observed_i))" },
          { kind: "formula", title: "RMSE", expression: "RMSE = sqrt((1/N) * sum((forecast_i - observed_i)^2))" },
          { kind: "formula", title: "Brier score", expression: "BS = (1/N) * sum((probability_i - outcome_i)^2)" },
          { kind: "formula", title: "Raw edge", expression: "edge = P_model - P_market" },
          { kind: "formula", title: "Adjusted edge", expression: "adjusted_edge = edge * confidence - fees - slippage" }
        ]
      }
    ]
  },
  {
    slug: "glossary",
    title: "Glossary",
    shortTitle: "Glossary",
    description: "Definitions for the weather, model, verification, and market terms used across the platform.",
    group: "Platform Architecture",
    sections: [
      {
        title: "Core Terms",
        blocks: [
          {
            kind: "table",
            columns: ["Term", "Definition"],
            rows: [
              ["Analysis", "The best estimate of the current Earth-system state after data assimilation."],
              ["Background", "A previous short-range forecast used as the first guess for assimilation."],
              ["Data assimilation", "Combining observations, model background, and error estimates into an analysis state."],
              ["Deterministic forecast", "A single forecast run from one initial state and model configuration."],
              ["Ensemble", "A set of related forecast runs used to estimate uncertainty and event probabilities."],
              ["Ensemble spread", "The amount of disagreement across ensemble members."],
              ["Forecast lead time", "The time between model initialization and the forecast valid time."],
              ["Forecast run", "A complete model cycle initialized at a specific time."],
              ["Grid spacing", "The horizontal distance between model grid points."],
              ["Numerical weather prediction", "Using physical equations and numerical methods to forecast weather."],
              ["Parameterization", "A simplified representation of processes smaller than the model grid."],
              ["Post-processing", "Calibrating, bias-correcting, and converting raw model output into usable products."],
              ["Brier score", "A score for probabilistic forecasts of binary events."],
              ["Skill score", "A comparison of model performance against a reference forecast."],
              ["Market probability", "A probability proxy inferred from prediction-market prices."],
              ["Model edge", "The difference between model-estimated probability and market-implied probability."],
              ["Confidence score", "A normalized score summarizing uncertainty, stability, and data quality."],
              ["Signal state", "A display label that communicates model-market alignment and data freshness."]
            ]
          }
        ]
      }
    ]
  }
];

export const docGroups = [
  {
    title: "Weather Prediction",
    pages: docs.filter((page) => page.group === "Weather Prediction")
  },
  {
    title: "Platform Architecture",
    pages: docs.filter((page) => page.group === "Platform Architecture")
  }
];

export const docsBySlug = new Map(docs.map((page) => [page.slug, page]));

export function getAdjacentDocs(slug: string) {
  const index = docs.findIndex((page) => page.slug === slug);
  return {
    previous: index > 0 ? docs[index - 1] : null,
    next: index >= 0 && index < docs.length - 1 ? docs[index + 1] : null
  };
}
