import type { CityMarketEvent } from "@/lib/markets/types";

type MockEventSeed = Omit<CityMarketEvent, "updatedAt"> & {
  /** Minutes before "now" that this event was last refreshed. */
  updatedMinutesAgo: number;
};

/**
 * Demo city weather market events. Probabilities and confidence are decimals;
 * derived metrics (edge, adjusted edge, net edge, signal) are computed in
 * calculations.ts. No external API keys are required to render this feed.
 */
const MOCK_EVENT_SEEDS: MockEventSeed[] = [
  {
    id: "wm-seoul-rain-10mm",
    city: "Seoul",
    country: "South Korea",
    countryCode: "KR",
    region: "Asia",
    lat: 37.5665,
    lon: 126.978,
    eventTitle: "Will rainfall exceed 10mm tomorrow?",
    eventCategory: "rain",
    eventWindow: "Tomorrow 00:00–23:59 KST",
    resolutionRule: "Resolves YES if KMA-reported 24h accumulated rainfall at Seoul station exceeds 10mm.",
    marketProbability: 0.58,
    aiProbability: 0.72,
    confidence: 0.65,
    volatility: 0.22,
    modelDisagreement: 0.18,
    modelTrend: "Rising",
    forecastModels: ["ECMWF IFS", "NOAA GFS", "ICON", "KMA GDAPS"],
    liquidity: 84000,
    source: "Demo market (Kalshi-style)",
    riskNotes: ["A stalled front could shift the heaviest band south of the settlement station."],
    updatedMinutesAgo: 6
  },
  {
    id: "wm-tokyo-maxtemp-30c",
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    region: "Asia",
    lat: 35.6762,
    lon: 139.6503,
    eventTitle: "Will max temperature exceed 30°C this week?",
    eventCategory: "temperature",
    eventWindow: "This week, Mon–Sun, JST",
    resolutionRule: "Resolves YES if JMA-reported daily maximum at Tokyo station exceeds 30.0°C on any day this week.",
    marketProbability: 0.41,
    aiProbability: 0.47,
    confidence: 0.58,
    volatility: 0.31,
    modelDisagreement: 0.27,
    modelTrend: "Rising",
    forecastModels: ["ECMWF IFS", "NOAA GFS", "JMA GSM"],
    liquidity: 152000,
    source: "Demo market (Kalshi-style)",
    riskNotes: ["Sea-breeze onset timing can cap station maxima a degree below model guidance."],
    updatedMinutesAgo: 14
  },
  {
    id: "wm-newyork-rain-saturday",
    city: "New York",
    country: "United States",
    countryCode: "US",
    region: "North America",
    lat: 40.7128,
    lon: -74.006,
    eventTitle: "Will it rain on Saturday?",
    eventCategory: "rain",
    eventWindow: "Saturday 00:00–23:59 ET",
    resolutionRule: "Resolves YES if NWS reports measurable precipitation (≥0.01 in) at Central Park on Saturday.",
    marketProbability: 0.33,
    aiProbability: 0.31,
    confidence: 0.62,
    volatility: 0.18,
    modelDisagreement: 0.15,
    modelTrend: "Stable",
    forecastModels: ["NOAA GFS", "ECMWF IFS", "NAM", "HRRR"],
    liquidity: 240000,
    source: "Demo market (Kalshi-style)",
    updatedMinutesAgo: 9
  },
  {
    id: "wm-london-gusts-40kmh",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    lat: 51.5072,
    lon: -0.1276,
    eventTitle: "Will wind gusts exceed 40 km/h?",
    eventCategory: "wind",
    eventWindow: "Tomorrow 06:00–22:00 BST",
    resolutionRule: "Resolves YES if Met Office-reported gusts at Heathrow exceed 40 km/h during the window.",
    marketProbability: 0.52,
    aiProbability: 0.38,
    confidence: 0.71,
    volatility: 0.14,
    modelDisagreement: 0.12,
    modelTrend: "Falling",
    forecastModels: ["ECMWF IFS", "Met Office UM", "ICON-EU"],
    liquidity: 67000,
    source: "Demo market (Polymarket-style)",
    riskNotes: ["Gust verification is station-specific; nearby exposed sites often read higher than Heathrow."],
    updatedMinutesAgo: 21
  },
  {
    id: "wm-singapore-thunderstorm-60",
    city: "Singapore",
    country: "Singapore",
    countryCode: "SG",
    region: "Asia",
    lat: 1.3521,
    lon: 103.8198,
    eventTitle: "Will thunderstorm probability exceed 60%?",
    eventCategory: "storm",
    eventWindow: "Tomorrow 12:00–20:00 SGT",
    resolutionRule: "Resolves YES if MSS issues a thunderstorm forecast probability above 60% for the afternoon window.",
    marketProbability: 0.66,
    aiProbability: 0.6,
    confidence: 0.3,
    volatility: 0.48,
    modelDisagreement: 0.44,
    modelTrend: "Volatile",
    forecastModels: ["ECMWF IFS", "Open-Meteo blend", "ACCESS-S"],
    liquidity: 18000,
    source: "Demo market (Polymarket-style)",
    riskNotes: [
      "Tropical convection is poorly resolved by global models; run-to-run swings are large.",
      "Resolution depends on an agency-issued probability rather than an observed outcome."
    ],
    updatedMinutesAgo: 4
  },
  {
    id: "wm-paris-temp-below-18c",
    city: "Paris",
    country: "France",
    countryCode: "FR",
    region: "Europe",
    lat: 48.8566,
    lon: 2.3522,
    eventTitle: "Will temperature stay below 18°C on Friday?",
    eventCategory: "temperature",
    eventWindow: "Friday 00:00–23:59 CEST",
    resolutionRule: "Resolves YES if the Météo-France daily maximum at Paris-Montsouris stays below 18.0°C on Friday.",
    marketProbability: 0.47,
    aiProbability: 0.55,
    confidence: 0.52,
    volatility: 0.26,
    modelDisagreement: 0.22,
    modelTrend: "Stable",
    forecastModels: ["ECMWF IFS", "ARPEGE", "ICON-EU"],
    liquidity: 43000,
    source: "Demo market (Kalshi-style)",
    updatedMinutesAgo: 32
  },
  {
    id: "wm-sydney-rain-5mm-weekend",
    city: "Sydney",
    country: "Australia",
    countryCode: "AU",
    region: "Oceania",
    lat: -33.8688,
    lon: 151.2093,
    eventTitle: "Will rainfall exceed 5mm this weekend?",
    eventCategory: "rain",
    eventWindow: "Sat 00:00 – Sun 23:59 AEST",
    resolutionRule: "Resolves YES if BOM-reported accumulated rainfall at Observatory Hill exceeds 5mm across the weekend.",
    marketProbability: 0.44,
    aiProbability: 0.37,
    confidence: 0.56,
    volatility: 0.29,
    modelDisagreement: 0.25,
    modelTrend: "Falling",
    forecastModels: ["ECMWF IFS", "ACCESS-G", "NOAA GFS"],
    liquidity: 39000,
    source: "Demo market (Polymarket-style)",
    updatedMinutesAgo: 18
  },
  {
    id: "wm-losangeles-maxtemp-32c",
    city: "Los Angeles",
    country: "United States",
    countryCode: "US",
    region: "North America",
    lat: 34.0522,
    lon: -118.2437,
    eventTitle: "Will max temperature exceed 32°C tomorrow?",
    eventCategory: "temperature",
    eventWindow: "Tomorrow 00:00–23:59 PT",
    resolutionRule: "Resolves YES if the NWS daily maximum at Downtown LA (USC) exceeds 32.2°C (90°F) tomorrow.",
    marketProbability: 0.61,
    aiProbability: 0.78,
    confidence: 0.74,
    volatility: 0.12,
    modelDisagreement: 0.1,
    modelTrend: "Rising",
    forecastModels: ["NOAA GFS", "ECMWF IFS", "HRRR", "NBM"],
    liquidity: 198000,
    source: "Demo market (Kalshi-style)",
    updatedMinutesAgo: 3
  },
  {
    id: "wm-berlin-rain-week",
    city: "Berlin",
    country: "Germany",
    countryCode: "DE",
    region: "Europe",
    lat: 52.52,
    lon: 13.405,
    eventTitle: "Will measurable rain occur this week?",
    eventCategory: "rain",
    eventWindow: "This week, Mon–Sun, CEST",
    resolutionRule: "Resolves YES if DWD reports measurable precipitation (≥0.1mm) at Berlin-Tempelhof on any day this week.",
    marketProbability: 0.72,
    aiProbability: 0.74,
    confidence: 0.68,
    volatility: 0.1,
    modelDisagreement: 0.09,
    modelTrend: "Stable",
    forecastModels: ["ICON", "ECMWF IFS", "NOAA GFS"],
    liquidity: 51000,
    source: "Demo market (Kalshi-style)",
    updatedMinutesAgo: 41
  },
  {
    id: "wm-hongkong-humidity-85",
    city: "Hong Kong",
    country: "Hong Kong",
    countryCode: "HK",
    region: "Asia",
    lat: 22.3193,
    lon: 114.1694,
    eventTitle: "Will humidity exceed 85% tomorrow evening?",
    eventCategory: "humidity",
    eventWindow: "Tomorrow 18:00–23:59 HKT",
    resolutionRule: "Resolves YES if HKO-reported relative humidity at the Observatory exceeds 85% during the evening window.",
    marketProbability: 0.58,
    aiProbability: 0.49,
    confidence: 0.41,
    volatility: 0.35,
    modelDisagreement: 0.38,
    modelTrend: "Volatile",
    forecastModels: ["ECMWF IFS", "Open-Meteo blend"],
    liquidity: 12000,
    source: "Demo market (Polymarket-style)",
    riskNotes: ["Humidity is a point measurement; harbor-side microclimate often diverges from model grid values."],
    updatedMinutesAgo: 11
  },
  {
    id: "wm-toronto-snow-2cm",
    city: "Toronto",
    country: "Canada",
    countryCode: "CA",
    region: "North America",
    lat: 43.6532,
    lon: -79.3832,
    eventTitle: "Will snowfall exceed 2cm tomorrow?",
    eventCategory: "snow",
    eventWindow: "Tomorrow 00:00–23:59 ET",
    resolutionRule: "Resolves YES if ECCC-reported snowfall accumulation at Toronto Pearson exceeds 2cm tomorrow.",
    marketProbability: 0.12,
    aiProbability: 0.07,
    confidence: 0.33,
    volatility: 0.52,
    modelDisagreement: 0.47,
    modelTrend: "Volatile",
    forecastModels: ["GEM", "NOAA GFS", "ECMWF IFS"],
    liquidity: 8000,
    source: "Demo market (Kalshi-style)",
    riskNotes: [
      "Marginal air-mass temperatures make rain/snow partitioning highly uncertain.",
      "Confidence is below the Avoid threshold; the raw edge is not actionable."
    ],
    updatedMinutesAgo: 55
  },
  {
    id: "wm-dubai-maxtemp-42c",
    city: "Dubai",
    country: "United Arab Emirates",
    countryCode: "AE",
    region: "Middle East",
    lat: 25.2048,
    lon: 55.2708,
    eventTitle: "Will max temperature exceed 42°C tomorrow?",
    eventCategory: "temperature",
    eventWindow: "Tomorrow 00:00–23:59 GST",
    resolutionRule: "Resolves YES if the NCM daily maximum at Dubai International exceeds 42.0°C tomorrow.",
    marketProbability: 0.81,
    aiProbability: 0.94,
    confidence: 0.82,
    volatility: 0.08,
    modelDisagreement: 0.06,
    modelTrend: "Stable",
    forecastModels: ["ECMWF IFS", "NOAA GFS", "ICON"],
    liquidity: 92000,
    source: "Demo market (Polymarket-style)",
    updatedMinutesAgo: 7
  },
  {
    id: "wm-chicago-gusts-50kmh",
    city: "Chicago",
    country: "United States",
    countryCode: "US",
    region: "North America",
    lat: 41.8781,
    lon: -87.6298,
    eventTitle: "Will wind gusts exceed 50 km/h on Thursday?",
    eventCategory: "wind",
    eventWindow: "Thursday 06:00–22:00 CT",
    resolutionRule: "Resolves YES if NWS-reported gusts at O'Hare exceed 50 km/h during the Thursday window.",
    marketProbability: 0.35,
    aiProbability: 0.22,
    confidence: 0.6,
    volatility: 0.2,
    modelDisagreement: 0.17,
    modelTrend: "Falling",
    forecastModels: ["NOAA GFS", "HRRR", "ECMWF IFS"],
    liquidity: 27000,
    source: "Demo market (Kalshi-style)",
    updatedMinutesAgo: 26
  },
  {
    id: "wm-mumbai-monsoon-rain-25mm",
    city: "Mumbai",
    country: "India",
    countryCode: "IN",
    region: "Asia",
    lat: 19.076,
    lon: 72.8777,
    eventTitle: "Will monsoon rainfall exceed 25mm tomorrow?",
    eventCategory: "rain",
    eventWindow: "Tomorrow 00:00–23:59 IST",
    resolutionRule: "Resolves YES if IMD-reported 24h rainfall at Santacruz exceeds 25mm tomorrow.",
    marketProbability: 0.77,
    aiProbability: 0.85,
    confidence: 0.49,
    volatility: 0.4,
    modelDisagreement: 0.33,
    modelTrend: "Rising",
    forecastModels: ["ECMWF IFS", "NOAA GFS", "IMD GFS"],
    liquidity: 34000,
    source: "Demo market (Polymarket-style)",
    riskNotes: ["Monsoon bursts are spatially patchy; city-average rain can miss the settlement gauge."],
    updatedMinutesAgo: 16
  }
];

/**
 * Materializes the demo feed with updatedAt timestamps relative to `now`, so
 * "updated X min ago" stays realistic on every request.
 */
export function buildMockCityMarketEvents(now: Date = new Date()): CityMarketEvent[] {
  return MOCK_EVENT_SEEDS.map(({ updatedMinutesAgo, ...event }) => ({
    ...event,
    updatedAt: new Date(now.getTime() - updatedMinutesAgo * 60_000).toISOString()
  }));
}
